name: lakes
description: Demonstrates building a layout for the "Lakes" app.

dependencies:
  flutter:
    sdk: flutter
  path_provider: "^0.4.0"

flutter:
  uses-material-design: true
  assets:
    - data/USD.json